# TCL File Generated by Component Editor 15.1
# Mon Jul 25 18:12:07 CST 2016
# DO NOT MODIFY


# 
# naive_mips_cpu "Naive MIPS CPU" v1.0
# Zhang YuXiang 2016.07.25.18:12:07
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module naive_mips_cpu
# 
set_module_property DESCRIPTION ""
set_module_property NAME naive_mips_cpu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Tsinghua
set_module_property AUTHOR "Zhang YuXiang"
set_module_property DISPLAY_NAME "Naive MIPS CPU"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL cpu_qsys_comp
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file cpu_qsys_comp.v VERILOG PATH cpu_qsys_comp.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL cpu_qsys_comp
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file cpu_qsys_comp.v VERILOG PATH cpu_qsys_comp.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point cpu_clock
# 
add_interface cpu_clock clock end
set_interface_property cpu_clock clockRate 0
set_interface_property cpu_clock ENABLED true
set_interface_property cpu_clock EXPORT_OF ""
set_interface_property cpu_clock PORT_NAME_MAP ""
set_interface_property cpu_clock CMSIS_SVD_VARIABLES ""
set_interface_property cpu_clock SVD_ADDRESS_GROUP ""

add_interface_port cpu_clock cpu_clock_clk clk Input 1


# 
# connection point debugger_clock
# 
add_interface debugger_clock clock end
set_interface_property debugger_clock clockRate 0
set_interface_property debugger_clock ENABLED true
set_interface_property debugger_clock EXPORT_OF ""
set_interface_property debugger_clock PORT_NAME_MAP ""
set_interface_property debugger_clock CMSIS_SVD_VARIABLES ""
set_interface_property debugger_clock SVD_ADDRESS_GROUP ""

add_interface_port debugger_clock debugger_clock_clk clk Input 1


# 
# connection point global_reset
# 
add_interface global_reset reset end
set_interface_property global_reset associatedClock cpu_clock
set_interface_property global_reset synchronousEdges DEASSERT
set_interface_property global_reset ENABLED true
set_interface_property global_reset EXPORT_OF ""
set_interface_property global_reset PORT_NAME_MAP ""
set_interface_property global_reset CMSIS_SVD_VARIABLES ""
set_interface_property global_reset SVD_ADDRESS_GROUP ""

add_interface_port global_reset reset_n reset_n Input 1


# 
# connection point inst_master
# 
add_interface inst_master avalon start
set_interface_property inst_master addressUnits SYMBOLS
set_interface_property inst_master associatedClock cpu_clock
set_interface_property inst_master associatedReset global_reset
set_interface_property inst_master bitsPerSymbol 8
set_interface_property inst_master burstOnBurstBoundariesOnly false
set_interface_property inst_master burstcountUnits WORDS
set_interface_property inst_master doStreamReads false
set_interface_property inst_master doStreamWrites false
set_interface_property inst_master holdTime 0
set_interface_property inst_master linewrapBursts false
set_interface_property inst_master maximumPendingReadTransactions 0
set_interface_property inst_master maximumPendingWriteTransactions 0
set_interface_property inst_master readLatency 0
set_interface_property inst_master readWaitTime 1
set_interface_property inst_master setupTime 0
set_interface_property inst_master timingUnits Cycles
set_interface_property inst_master writeWaitTime 0
set_interface_property inst_master ENABLED true
set_interface_property inst_master EXPORT_OF ""
set_interface_property inst_master PORT_NAME_MAP ""
set_interface_property inst_master CMSIS_SVD_VARIABLES ""
set_interface_property inst_master SVD_ADDRESS_GROUP ""

add_interface_port inst_master inst_master_read read Output 1
add_interface_port inst_master inst_master_write write Output 1
add_interface_port inst_master inst_master_address address Output 32
add_interface_port inst_master inst_master_byteenable byteenable Output 4
add_interface_port inst_master inst_master_readdata readdata Input 32
add_interface_port inst_master inst_master_writedata writedata Output 32
add_interface_port inst_master inst_master_waitrequest waitrequest Input 1


# 
# connection point data_master
# 
add_interface data_master avalon start
set_interface_property data_master addressUnits SYMBOLS
set_interface_property data_master associatedClock cpu_clock
set_interface_property data_master associatedReset global_reset
set_interface_property data_master bitsPerSymbol 8
set_interface_property data_master burstOnBurstBoundariesOnly false
set_interface_property data_master burstcountUnits WORDS
set_interface_property data_master doStreamReads false
set_interface_property data_master doStreamWrites false
set_interface_property data_master holdTime 0
set_interface_property data_master linewrapBursts false
set_interface_property data_master maximumPendingReadTransactions 0
set_interface_property data_master maximumPendingWriteTransactions 0
set_interface_property data_master readLatency 0
set_interface_property data_master readWaitTime 1
set_interface_property data_master setupTime 0
set_interface_property data_master timingUnits Cycles
set_interface_property data_master writeWaitTime 0
set_interface_property data_master ENABLED true
set_interface_property data_master EXPORT_OF ""
set_interface_property data_master PORT_NAME_MAP ""
set_interface_property data_master CMSIS_SVD_VARIABLES ""
set_interface_property data_master SVD_ADDRESS_GROUP ""

add_interface_port data_master data_master_read read Output 1
add_interface_port data_master data_master_write write Output 1
add_interface_port data_master data_master_address address Output 32
add_interface_port data_master data_master_byteenable byteenable Output 4
add_interface_port data_master data_master_readdata readdata Input 32
add_interface_port data_master data_master_writedata writedata Output 32
add_interface_port data_master data_master_waitrequest waitrequest Input 1


# 
# connection point inr_irq0
# 
add_interface inr_irq0 interrupt start
set_interface_property inr_irq0 associatedAddressablePoint data_master
set_interface_property inr_irq0 associatedClock cpu_clock
set_interface_property inr_irq0 associatedReset global_reset
set_interface_property inr_irq0 irqScheme INDIVIDUAL_REQUESTS
set_interface_property inr_irq0 ENABLED true
set_interface_property inr_irq0 EXPORT_OF ""
set_interface_property inr_irq0 PORT_NAME_MAP ""
set_interface_property inr_irq0 CMSIS_SVD_VARIABLES ""
set_interface_property inr_irq0 SVD_ADDRESS_GROUP ""

add_interface_port inr_irq0 inr_irq0_irq irq Input 5


# 
# connection point debugger
# 
add_interface debugger conduit end
set_interface_property debugger associatedClock cpu_clock
set_interface_property debugger associatedReset ""
set_interface_property debugger ENABLED true
set_interface_property debugger EXPORT_OF ""
set_interface_property debugger PORT_NAME_MAP ""
set_interface_property debugger CMSIS_SVD_VARIABLES ""
set_interface_property debugger SVD_ADDRESS_GROUP ""

add_interface_port debugger dbg_txd dbg_txd Output 1
add_interface_port debugger dbg_rxd dbg_rxd Input 1


# 
# connection point trace
# 
add_interface trace conduit end
set_interface_property trace associatedClock cpu_clock
set_interface_property trace associatedReset ""
set_interface_property trace ENABLED true
set_interface_property trace EXPORT_OF ""
set_interface_property trace PORT_NAME_MAP ""
set_interface_property trace CMSIS_SVD_VARIABLES ""
set_interface_property trace SVD_ADDRESS_GROUP ""

add_interface_port trace trace_data trace_data Output 128
add_interface_port trace trace_en trace_en Output 2


# 
# connection point io_master
# 
add_interface io_master avalon start
set_interface_property io_master addressUnits SYMBOLS
set_interface_property io_master associatedClock cpu_clock
set_interface_property io_master associatedReset global_reset
set_interface_property io_master bitsPerSymbol 8
set_interface_property io_master burstOnBurstBoundariesOnly false
set_interface_property io_master burstcountUnits WORDS
set_interface_property io_master doStreamReads false
set_interface_property io_master doStreamWrites false
set_interface_property io_master holdTime 0
set_interface_property io_master linewrapBursts false
set_interface_property io_master maximumPendingReadTransactions 0
set_interface_property io_master maximumPendingWriteTransactions 0
set_interface_property io_master readLatency 0
set_interface_property io_master readWaitTime 1
set_interface_property io_master setupTime 0
set_interface_property io_master timingUnits Cycles
set_interface_property io_master writeWaitTime 0
set_interface_property io_master ENABLED true
set_interface_property io_master EXPORT_OF ""
set_interface_property io_master PORT_NAME_MAP ""
set_interface_property io_master CMSIS_SVD_VARIABLES ""
set_interface_property io_master SVD_ADDRESS_GROUP ""

add_interface_port io_master io_master_address address Output 32
add_interface_port io_master io_master_byteenable byteenable Output 4
add_interface_port io_master io_master_read read Output 1
add_interface_port io_master io_master_readdata readdata Input 32
add_interface_port io_master io_master_waitrequest waitrequest Input 1
add_interface_port io_master io_master_write write Output 1
add_interface_port io_master io_master_writedata writedata Output 32

