# TCL File Generated by Component Editor 15.1
# Fri Jul 22 22:43:06 CST 2016
# DO NOT MODIFY


# 
# trace_logger "Trace Logger" v1.0
# Zhang Yuxiang 2016.07.22.22:43:06
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module trace_logger
# 
set_module_property DESCRIPTION ""
set_module_property NAME trace_logger
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Tsinghua
set_module_property AUTHOR "Zhang Yuxiang"
set_module_property DISPLAY_NAME "Trace Logger"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL logger
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file logger.v VERILOG PATH logger.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL logger
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file logger.v VERILOG PATH logger.v

# 
# parameters
# 


# 
# display items
# 


# 
# connection point trace_out
# 
add_interface trace_out avalon_streaming start
set_interface_property trace_out associatedClock clk_dout
set_interface_property trace_out associatedReset reset
set_interface_property trace_out dataBitsPerSymbol 8
set_interface_property trace_out errorDescriptor ""
set_interface_property trace_out firstSymbolInHighOrderBits true
set_interface_property trace_out maxChannel 0
set_interface_property trace_out readyLatency 0
set_interface_property trace_out ENABLED true
set_interface_property trace_out EXPORT_OF ""
set_interface_property trace_out PORT_NAME_MAP ""
set_interface_property trace_out CMSIS_SVD_VARIABLES ""
set_interface_property trace_out SVD_ADDRESS_GROUP ""

add_interface_port trace_out trace_out_data data Output 128
add_interface_port trace_out trace_out_ready ready Input 1
add_interface_port trace_out trace_out_valid valid Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk_din
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point trace_in
# 
add_interface trace_in conduit end
set_interface_property trace_in associatedClock clk_din
set_interface_property trace_in associatedReset reset
set_interface_property trace_in ENABLED true
set_interface_property trace_in EXPORT_OF ""
set_interface_property trace_in PORT_NAME_MAP ""
set_interface_property trace_in CMSIS_SVD_VARIABLES ""
set_interface_property trace_in SVD_ADDRESS_GROUP ""

add_interface_port trace_in trace_data trace_data Input 128
add_interface_port trace_in trace_en trace_en Input 2
add_interface_port trace_in full full Output 1


# 
# connection point clk_din
# 
add_interface clk_din clock end
set_interface_property clk_din clockRate 0
set_interface_property clk_din ENABLED true
set_interface_property clk_din EXPORT_OF ""
set_interface_property clk_din PORT_NAME_MAP ""
set_interface_property clk_din CMSIS_SVD_VARIABLES ""
set_interface_property clk_din SVD_ADDRESS_GROUP ""

add_interface_port clk_din clk_clk clk Input 1


# 
# connection point clk_dout
# 
add_interface clk_dout clock end
set_interface_property clk_dout clockRate 0
set_interface_property clk_dout ENABLED true
set_interface_property clk_dout EXPORT_OF ""
set_interface_property clk_dout PORT_NAME_MAP ""
set_interface_property clk_dout CMSIS_SVD_VARIABLES ""
set_interface_property clk_dout SVD_ADDRESS_GROUP ""

add_interface_port clk_dout clk_dout_clk clk Input 1

