/************************************************************\
 **  Copyright (c) 2011-2017 Anlogic, Inc.
 **  All Right Reserved.
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	/home/zhang/NaiveMIPS-HDL/anlogic/naivemips/al_ip/sys_pll.v
 ** Date	:	2018 08 10
 ** TD version	:	4.1.670
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:             24.000Mhz
//	Clock multiplication factor: 6
//	Clock division factor:       13
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 9.969  MHZ	| 0  DEG     
//		C1        	| 9.969  MHZ	| 0  DEG     
//		C2        	| 11.077 MHZ	| 0  DEG     
//		C3        	| 9.969  MHZ	| 0  DEG     
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs
`default_nettype wire
module sys_pll(refclk,
		reset,
		extlock,
		clk0_out,
		clk1_out,
		clk2_out,
		clk3_out);

	input refclk;
	input reset;
	output extlock;
	output clk0_out;
	output clk1_out;
	output clk2_out;
	output clk3_out;

	wire clk2_buf;

	EG_LOGIC_BUFG bufg_feedback( .i(clk2_buf), .o(clk2_out) );

	EG_PHY_PLL #(.DYNCFG("DISABLE"),
		.FIN("24.000"),
		.FEEDBK_PATH("CLKC2_EXT"),
		.STDBY_ENABLE("DISABLE"),
		.PLLRST_ENA("ENABLE"),
		.SYNC_ENABLE("ENABLE"),
		.DERIVE_PLL_CLOCKS("ENABLE"),
		.GEN_BASIC_CLOCK("ENABLE"),
		.GMC_GAIN(6),
		.ICP_CURRENT(3),
		.KVCO(6),
		.LPF_CAPACITOR(3),
		.LPF_RESISTOR(2),
		.REFCLK_DIV(13),
		.FBCLK_DIV(6),
		.CLKC0_ENABLE("ENABLE"),
		.CLKC0_DIV(100),
		.CLKC0_CPHASE(100),
		.CLKC0_FPHASE(0),
		.CLKC1_ENABLE("ENABLE"),
		.CLKC1_DIV(100),
		.CLKC1_CPHASE(100),
		.CLKC1_FPHASE(0),
		.CLKC2_ENABLE("ENABLE"),
		.CLKC2_DIV(90),
		.CLKC2_CPHASE(90),
		.CLKC2_FPHASE(0),
		.CLKC3_ENABLE("ENABLE"),
		.CLKC3_DIV(100),
		.CLKC3_CPHASE(100),
		.CLKC3_FPHASE(0)	)
	pll_inst (.refclk(refclk),
		.reset(reset),
		.stdby(1'b0),
		.extlock(extlock),
		.psclk(1'b0),
		.psdown(1'b0),
		.psstep(1'b0),
		.psclksel(3'b000),
		.psdone(open),
		.dclk(1'b0),
		.dcs(1'b0),
		.dwe(1'b0),
		.di(8'b00000000),
		.daddr(6'b000000),
		.do({open, open, open, open, open, open, open, open}),
		.fbclk(clk2_out),
		.clkc({open, clk3_out, clk2_buf, clk1_out, clk0_out}));

endmodule
