	soc_system u0 (
		.clk_clk                               (<connected-to-clk_clk>),                               //             clk.clk
		.clk_cpu_clk                           (<connected-to-clk_cpu_clk>),                           //         clk_cpu.clk
		.clk_other_clk                         (<connected-to-clk_other_clk>),                         //       clk_other.clk
		.clk_uart_clk                          (<connected-to-clk_uart_clk>),                          //        clk_uart.clk
		.debugger_dbg_txd                      (<connected-to-debugger_dbg_txd>),                      //        debugger.dbg_txd
		.debugger_dbg_rxd                      (<connected-to-debugger_dbg_rxd>),                      //                .dbg_rxd
		.hps_0_h2f_reset_reset_n               (<connected-to-hps_0_h2f_reset_reset_n>),               // hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>), //    hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),   //                .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),   //                .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),   //                .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),   //                .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),   //                .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),   //                .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC    (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),    //                .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>), //                .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>), //                .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>), //                .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),   //                .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),   //                .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),   //                .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_qspi_inst_IO0     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO0>),     //                .hps_io_qspi_inst_IO0
		.hps_0_hps_io_hps_io_qspi_inst_IO1     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO1>),     //                .hps_io_qspi_inst_IO1
		.hps_0_hps_io_hps_io_qspi_inst_IO2     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO2>),     //                .hps_io_qspi_inst_IO2
		.hps_0_hps_io_hps_io_qspi_inst_IO3     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_IO3>),     //                .hps_io_qspi_inst_IO3
		.hps_0_hps_io_hps_io_qspi_inst_SS0     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_SS0>),     //                .hps_io_qspi_inst_SS0
		.hps_0_hps_io_hps_io_qspi_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_qspi_inst_CLK>),     //                .hps_io_qspi_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_CMD     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),     //                .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),      //                .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),      //                .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),     //                .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),      //                .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3      (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),      //                .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),      //                .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),      //                .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),      //                .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),      //                .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),      //                .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),      //                .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),      //                .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7      (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),      //                .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),     //                .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),     //                .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),     //                .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT     (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),     //                .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK    (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),    //                .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI   (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),   //                .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO   (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),   //                .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0    (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),    //                .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),     //                .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX     (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),     //                .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),     //                .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),     //                .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),     //                .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),     //                .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),  //                .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),  //                .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),  //                .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO48  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO48>),  //                .hps_io_gpio_inst_GPIO48
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),  //                .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),  //                .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),  //                .hps_io_gpio_inst_GPIO61
		.hps_0_uart1_cts                       (<connected-to-hps_0_uart1_cts>),                       //     hps_0_uart1.cts
		.hps_0_uart1_dsr                       (<connected-to-hps_0_uart1_dsr>),                       //                .dsr
		.hps_0_uart1_dcd                       (<connected-to-hps_0_uart1_dcd>),                       //                .dcd
		.hps_0_uart1_ri                        (<connected-to-hps_0_uart1_ri>),                        //                .ri
		.hps_0_uart1_dtr                       (<connected-to-hps_0_uart1_dtr>),                       //                .dtr
		.hps_0_uart1_rts                       (<connected-to-hps_0_uart1_rts>),                       //                .rts
		.hps_0_uart1_out1_n                    (<connected-to-hps_0_uart1_out1_n>),                    //                .out1_n
		.hps_0_uart1_out2_n                    (<connected-to-hps_0_uart1_out2_n>),                    //                .out2_n
		.hps_0_uart1_rxd                       (<connected-to-hps_0_uart1_rxd>),                       //                .rxd
		.hps_0_uart1_txd                       (<connected-to-hps_0_uart1_txd>),                       //                .txd
		.led_export                            (<connected-to-led_export>),                            //             led.export
		.memory_mem_a                          (<connected-to-memory_mem_a>),                          //          memory.mem_a
		.memory_mem_ba                         (<connected-to-memory_mem_ba>),                         //                .mem_ba
		.memory_mem_ck                         (<connected-to-memory_mem_ck>),                         //                .mem_ck
		.memory_mem_ck_n                       (<connected-to-memory_mem_ck_n>),                       //                .mem_ck_n
		.memory_mem_cke                        (<connected-to-memory_mem_cke>),                        //                .mem_cke
		.memory_mem_cs_n                       (<connected-to-memory_mem_cs_n>),                       //                .mem_cs_n
		.memory_mem_ras_n                      (<connected-to-memory_mem_ras_n>),                      //                .mem_ras_n
		.memory_mem_cas_n                      (<connected-to-memory_mem_cas_n>),                      //                .mem_cas_n
		.memory_mem_we_n                       (<connected-to-memory_mem_we_n>),                       //                .mem_we_n
		.memory_mem_reset_n                    (<connected-to-memory_mem_reset_n>),                    //                .mem_reset_n
		.memory_mem_dq                         (<connected-to-memory_mem_dq>),                         //                .mem_dq
		.memory_mem_dqs                        (<connected-to-memory_mem_dqs>),                        //                .mem_dqs
		.memory_mem_dqs_n                      (<connected-to-memory_mem_dqs_n>),                      //                .mem_dqs_n
		.memory_mem_odt                        (<connected-to-memory_mem_odt>),                        //                .mem_odt
		.memory_mem_dm                         (<connected-to-memory_mem_dm>),                         //                .mem_dm
		.memory_oct_rzqin                      (<connected-to-memory_oct_rzqin>),                      //                .oct_rzqin
		.reset_reset_n                         (<connected-to-reset_reset_n>),                         //           reset.reset_n
		.rst_cpu_reset_n                       (<connected-to-rst_cpu_reset_n>),                       //         rst_cpu.reset_n
		.rst_other_reset_n                     (<connected-to-rst_other_reset_n>),                     //       rst_other.reset_n
		.sdram_addr                            (<connected-to-sdram_addr>),                            //           sdram.addr
		.sdram_ba                              (<connected-to-sdram_ba>),                              //                .ba
		.sdram_cas_n                           (<connected-to-sdram_cas_n>),                           //                .cas_n
		.sdram_cke                             (<connected-to-sdram_cke>),                             //                .cke
		.sdram_cs_n                            (<connected-to-sdram_cs_n>),                            //                .cs_n
		.sdram_dq                              (<connected-to-sdram_dq>),                              //                .dq
		.sdram_dqm                             (<connected-to-sdram_dqm>),                             //                .dqm
		.sdram_ras_n                           (<connected-to-sdram_ras_n>),                           //                .ras_n
		.sdram_we_n                            (<connected-to-sdram_we_n>),                            //                .we_n
		.sdram_clk_clk                         (<connected-to-sdram_clk_clk>),                         //       sdram_clk.clk
		.sw_export                             (<connected-to-sw_export>),                             //              sw.export
		.uart_rxd                              (<connected-to-uart_rxd>),                              //            uart.rxd
		.uart_txd                              (<connected-to-uart_txd>),                              //                .txd
		.usb_bus_tcm_address_out               (<connected-to-usb_bus_tcm_address_out>),               //         usb_bus.tcm_address_out
		.usb_bus_tcm_read_n_out                (<connected-to-usb_bus_tcm_read_n_out>),                //                .tcm_read_n_out
		.usb_bus_tcm_reset_n_out               (<connected-to-usb_bus_tcm_reset_n_out>),               //                .tcm_reset_n_out
		.usb_bus_tcm_write_n_out               (<connected-to-usb_bus_tcm_write_n_out>),               //                .tcm_write_n_out
		.usb_bus_tcm_data_out                  (<connected-to-usb_bus_tcm_data_out>),                  //                .tcm_data_out
		.usb_bus_tcm_chipselect_n_out          (<connected-to-usb_bus_tcm_chipselect_n_out>)           //                .tcm_chipselect_n_out
	);

