# TCL File Generated by Component Editor 15.1
# Sun May 22 08:31:01 GMT 2016
# DO NOT MODIFY


# 
# Cache "Naive Cache" v1.0
#  2016.05.22.08:31:01
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module Cache
# 
set_module_property DESCRIPTION ""
set_module_property NAME Cache
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Tsinghua
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Naive Cache"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Cache
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE true
add_fileset_file Cache.v VERILOG PATH Cache.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point burst_master
# 
add_interface burst_master avalon start
set_interface_property burst_master addressUnits SYMBOLS
set_interface_property burst_master associatedClock Clock
set_interface_property burst_master associatedReset Reset
set_interface_property burst_master bitsPerSymbol 8
set_interface_property burst_master burstOnBurstBoundariesOnly false
set_interface_property burst_master burstcountUnits SYMBOLS
set_interface_property burst_master doStreamReads false
set_interface_property burst_master doStreamWrites false
set_interface_property burst_master holdTime 0
set_interface_property burst_master linewrapBursts false
set_interface_property burst_master maximumPendingReadTransactions 0
set_interface_property burst_master maximumPendingWriteTransactions 0
set_interface_property burst_master readLatency 0
set_interface_property burst_master readWaitTime 1
set_interface_property burst_master setupTime 0
set_interface_property burst_master timingUnits Cycles
set_interface_property burst_master writeWaitTime 0
set_interface_property burst_master ENABLED true
set_interface_property burst_master EXPORT_OF ""
set_interface_property burst_master PORT_NAME_MAP ""
set_interface_property burst_master CMSIS_SVD_VARIABLES ""
set_interface_property burst_master SVD_ADDRESS_GROUP ""

add_interface_port burst_master avalon_master_address address Output 32
add_interface_port burst_master avalon_master_burstcount burstcount Output 1
add_interface_port burst_master avalon_master_readdata readdata Input 32
add_interface_port burst_master avalon_master_writedata writedata Output 32
add_interface_port burst_master avalon_master_waitrequest waitrequest Input 1
add_interface_port burst_master avalon_master_read read Output 1
add_interface_port burst_master avalon_master_write write Output 1
add_interface_port burst_master avalon_master_readdatavalid readdatavalid Input 1


# 
# connection point Reset
# 
add_interface Reset reset end
set_interface_property Reset associatedClock Clock
set_interface_property Reset synchronousEdges DEASSERT
set_interface_property Reset ENABLED true
set_interface_property Reset EXPORT_OF ""
set_interface_property Reset PORT_NAME_MAP ""
set_interface_property Reset CMSIS_SVD_VARIABLES ""
set_interface_property Reset SVD_ADDRESS_GROUP ""

add_interface_port Reset rst_n reset_n Input 1


# 
# connection point Clock
# 
add_interface Clock clock end
set_interface_property Clock clockRate 0
set_interface_property Clock ENABLED true
set_interface_property Clock EXPORT_OF ""
set_interface_property Clock PORT_NAME_MAP ""
set_interface_property Clock CMSIS_SVD_VARIABLES ""
set_interface_property Clock SVD_ADDRESS_GROUP ""

add_interface_port Clock clk clk Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits SYMBOLS
set_interface_property avalon_slave associatedClock Clock
set_interface_property avalon_slave associatedReset Reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits SYMBOLS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avalon_slave_address address Input 32
add_interface_port avalon_slave avalon_slave_read read Input 1
add_interface_port avalon_slave avalon_slave_write write Input 1
add_interface_port avalon_slave avalon_slave_readdata readdata Output 32
add_interface_port avalon_slave avalon_slave_writedata writedata Input 32
add_interface_port avalon_slave avalon_slave_waitrequest waitrequest Output 1
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

